server:
  port: 8100
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  

resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 20s
  retry:
    instances:
      book-service:
        max-attempts: 5
      default:
        max-attempts: 4  
        
spring:
  application:
    name: book-microservice  
    
  #MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/dbbook?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    
  #JPA  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format-sql: true
    show-sql: true
  
  #SQL  
  sql:
    init:
      mode: always   
      
  #Flyway
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: dbbook  
    user: root
    password: root123     
          