server:
  port: 8000
  
spring:
  application:
    name: cambio-service  
    
  #MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/dbcarros?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
  
  #JPA  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format-sql: true
        ddl-auto: auto
    show-sql: true
    
  #SQL
  sql:
    init:
      mode: always  
      
  #Flyway
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: currency_exchange     
    user: root
    password: root123
 